# Secvisogram Dependabot configuration file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "production"
