name: 'markdownlint documentation files'

on: [pull_request]

jobs:
  verify-markdown-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: .github/lint/.markdownlint.yml
