name: Run Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install hunspell
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run test-report
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: success() || failure()
        with:
          name: Mocha Tests
          path: test-results.json
          reporter: mocha-json
      - run: npm run test-coverage-lcov
      - name: c8 coverage report
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
